name: Build-Test
on: workflow_dispatch
jobs:
  Linux:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: sqlite-build
      - name: Checkout sqlite
        uses: actions/checkout@v4
        with:
          repository: sqlite/sqlite
          ref: version-3.43.1
          path: sqlite
      - name: Install deps
        run: |
          sudo apt-get -y install tk-dev gcc-10 g++-10
          alias gcc='gcc-10'
          alias g++='g++-10'
          export CC=`which gcc-10`
          export CXX=`which gcc-10`
      - name: Build
        run: |
          cd sqlite
          mkdir build
          cd build
          ../configure --prefix `pwd`/install
          make -j2
          make lib_install
      - name: Generate tar
        run: |
          echo ${{ github.sha }} > Release.txt
          cp Release.txt ./sqlite/build/install/lib
          cp ./sqlite/build/sqlite3.h ./sqlite/build/install/lib
          tar -czvf sqlite.${{}}.tar.gz -C ./sqlite/build/install/lib .