name: Windows
permissions:
  contents: write
on: workflow_dispatch
jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-2022
    steps:
      - name: Checkout tcltk/tcl
        uses: actions/checkout@v4
        with:
          repository: tcltk/tcl
          ref: core-8-6-13
          path: tcl
      - name: Checkout sqlite
        uses: actions/checkout@v4
        with:
          repository: sqlite/sqlite
          ref: version-3.43.1
          path: sqlite
      - name: Init MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build tcl
        run: |
          cd ./tcl/win
          nmake -f makefile.vc release
          nmake /f makefile.vc INSTALLDIR=./install install
          copy install/lib/tcl86t.lib install/lib/tcl86.lib
          copy install/bin/tclsh86t.exe install/bin/tclsh.exe
          echo "$GITHUB_WORKSPACE/tcl/install/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          $Env:TCLDIR = "$GITHUB_WORKSPACE/tcl/install"
      - name: Build sqlite
        run: |
          cd ./sqlite
          nmake /f makefile.msc dll
      - name: Generate zip
        run: |
          echo ${{ github.sha }} > Release.txt
          Compress-Archive -Path ./sqlite/sqlite3.h,./sqlite/sqlite3.dll,./sqlite/sqlite3.lib,./sqlite/sqlite3.pdb,./Release.txt -DestinationPath sqlite3.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: sqlite3.zip
          
